export default [
  {
    action: 'MR',
    color: 'light',
    position: 1,
    size: 'small',
    id: 'mr',
  },
  {
    action: 'M-',
    color: 'light',
    position: 2,
    size: 'small',
    id: 'mMinus',
  },
  {
    action: 'M+',
    color: 'light',
    position: 3,
    size: 'small',
    id: 'mPlus',
  },
  {
    action: 'CE',
    color: 'light',
    position: 4,
    size: 'small',
    id: 'ce',
  },
  {
    action: 'ON / C',
    color: 'red',
    position: 5,
    size: 'small',
    id: 'onButton',
  },
  {
    action: 7,
    color: 'dark',
    position: 6,
    size: 'normal',
    id: 'number7',
  },
  {
    action: 8,
    color: 'dark',
    position: 7,
    size: 'normal',
    id: 'number8',
  },
  {
    action: 9,
    color: 'dark',
    position: 8,
    size: 'normal',
    id: 'number9',
  },
  {
    action: '%',
    color: 'light',
    position: 9,
    size: 'normal',
    id: 'percentage',
  },
  {
    action: 'root',
    color: 'light',
    position: 10,
    size: 'normal',
    id: 'root',
  },
  {
    action: 4,
    color: 'dark',
    position: 11,
    size: 'normal',
    id: 'number4',
  },
  {
    action: 5,
    color: 'dark',
    position: 12,
    size: 'normal',
    id: 'number5',
  },
  {
    action: 6,
    color: 'dark',
    position: 13,
    size: 'normal',
    id: 'number6',
  },
  {
    action: 'X',
    color: 'light',
    position: 14,
    size: 'normal',
    id: 'x',
  },
  {
    action: '/',
    color: 'light',
    position: 15,
    size: 'normal',
    id: 'divide',
  },
  {
    action: 1,
    color: 'dark',
    position: 16,
    size: 'normal',
    id: 'number1',
  },
  {
    action: 2,
    color: 'dark',
    position: 17,
    size: 'normal',
    id: 'number2',
  },
  {
    action: 3,
    color: 'dark',
    position: 18,
    size: 'normal',
    id: 'number3',
  },
  {
    action: '+',
    color: 'light',
    position: 19,
    size: 'huge',
    id: 'plus',
  },
  {
    action: '-',
    color: 'light',
    position: 20,
    size: 'normal',
    id: 'minus',
  },
  {
    action: 0,
    color: 'dark',
    position: 21,
    size: 'normal',
    id: 'number0',
  },
  {
    action: '.',
    color: 'dark',
    position: 22,
    size: 'normal',
    id: 'dot',
  },
  {
    action: '+/-',
    color: 'dark',
    position: 23,
    size: 'normal',
    id: 'changeSign',
  },
  {
    action: '=',
    color: 'light',
    position: 24,
    size: 'normal',
    id: 'equal',
  },
];
